"""Compare an oracle trace (tools/oracle/trace.py, from PCSX2) with an `nfgame --trace` replay.

  compare.py make-inputs oracle.jsonl out.inputs      write the nfgame --inputs file for a trace
                                                      (pad, frame rate, recorded foot height, previous position)
  compare.py diff oracle.jsonl replay.jsonl [--name scenario]   per-frame error report
  compare.py table oracle_dir replay_dir              one summary row per scenario (*.jsonl)

Workflow (docs/oracle.md): record scenario -> make-inputs -> `nfgame <gamedir> 07000024.bin
--inputs x.inputs --trace x.replay.jsonl` -> diff (add --sync to re-seat the player on the recorded
position before every frame: a per-frame model error instead of an accumulated one). The replay starts from the oracle's first record
(standing still) and is fed the pad the game saw on every following frame; frames the tracer missed
take the pad of the next recorded frame and the rate of the previous one. Units are game units (metres); the target is ~1 cm.
"""
import argparse
import json
import math
import os
import struct
import sys


def load(path):
    with open(path) as f:
        return [json.loads(line) for line in f if line.strip()]


def bl_float(rec, key, offset):
    blob = bytes.fromhex(rec[key])
    return struct.unpack_from("<f", blob, offset)[0]


def make_inputs(trace_path, out_path):
    recs = load(trace_path)
    first = recs[0]
    pitch = bl_float(first, "bl8a0", 0x8A8 - 0x8A0)
    gny = bl_float(first, "bl100", 0x110 - 0x100) if "bl100" in first else 1.0
    by_frame = {r["frame"]: r for r in recs}
    lines = []
    with open(out_path, "w") as f:
        f.write("# generated by compare.py make-inputs from %s\n" % os.path.basename(trace_path))
        f.write("start %.9g %.9g %.9g %.9g %.9g %.9g\n" % (*first["pos"], first["yaw"], pitch, gny))
        following = None
        for frame in range(recs[-1]["frame"], first["frame"], -1):   # backwards: a missed frame takes the next pad and the previous frame rate
            following = by_frame.get(frame, following)
            lines.append((frame, following))
        lines.reverse()
        rate = first.get("rate", 30.0)
        height = struct.unpack_from("<f", bytes.fromhex(first["cb"]), 0xCC)[0]
        for frame, rec in lines:
            rate = by_frame[frame].get("rate", rate) if frame in by_frame else rate   # ...but the previous rate
            pad = rec["pad"]
            src = by_frame.get(frame)
            if src:
                height = struct.unpack_from("<f", bytes.fromhex(src["cb"]), 0xCC)[0]
            before = by_frame.get(frame - 1)
            sync = " %.9g %.9g %.9g" % tuple(before["pos"]) if before else ""
            f.write("%d %x %d %d %d %d %g %.9g%s\n" % (frame, pad["w"], *pad["s"], rate, height, sync))
    return len(recs)


def angle_diff(a, b):
    d = (a - b + math.pi) % (2 * math.pi) - math.pi
    return d


def diff(oracle_path, replay_path):
    oracle = load(oracle_path)
    replay = {r["frame"]: r for r in load(replay_path)}
    rows = []
    for o in oracle[1:]:
        r = replay.get(o["frame"])
        if r is None:
            continue
        dpos = [a - b for a, b in zip(r["pos"], o["pos"])]
        act = max(abs(a - b) for a, b in zip(r["act"], o["act"]))
        flg = sum(1 for x, y in zip(bytes.fromhex(r["flg"]), bytes.fromhex(o["flg"])) if x != y)
        rows.append({
            "frame": o["frame"],
            "pos_err": math.sqrt(sum(d * d for d in dpos)),
            "dy": dpos[1],
            "yaw_err": abs(angle_diff(r["yaw"], o["yaw"])),
            "act_err": act,
            "flag_mismatch": flg,
            "oracle": o,
            "replay": r,
        })
    return rows


def summarize(name, rows, threshold=0.01):
    if not rows:
        return f"{name}: no overlapping frames"
    max_pos = max(r["pos_err"] for r in rows)
    end_pos = rows[-1]["pos_err"]
    first_bad = next((r["frame"] - rows[0]["frame"] + 1 for r in rows if r["pos_err"] > threshold), None)
    travel = math.dist(rows[0]["oracle"]["pos"], rows[-1]["oracle"]["pos"])
    return (f"{name:<14} frames={len(rows):<4} max_pos={max_pos * 100:8.3f} cm  end_pos={end_pos * 100:8.3f} cm  "
            f"max_yaw={max(r['yaw_err'] for r in rows):.6f} rad  max_act={max(r['act_err'] for r in rows):.2e}  "
            f"flag_mismatch={sum(r['flag_mismatch'] for r in rows)}  first>1cm={first_bad}  net_travel={travel:.2f}")


def main():
    ap = argparse.ArgumentParser()
    sub = ap.add_subparsers(dest="cmd", required=True)
    p = sub.add_parser("make-inputs")
    p.add_argument("trace")
    p.add_argument("out")
    p = sub.add_parser("diff")
    p.add_argument("oracle")
    p.add_argument("replay")
    p.add_argument("--name")
    p.add_argument("--verbose", action="store_true", help="print every frame")
    p = sub.add_parser("table")
    p.add_argument("oracle_dir")
    p.add_argument("replay_dir")
    args = ap.parse_args()

    if args.cmd == "make-inputs":
        n = make_inputs(args.trace, args.out)
        print(f"{n} records -> {args.out}")
    elif args.cmd == "diff":
        rows = diff(args.oracle, args.replay)
        print(summarize(args.name or os.path.basename(args.oracle), rows))
        if args.verbose:
            for r in rows:
                print("%d pos_err=%.5f dy=%+.5f yaw_err=%.6f act_err=%.2e" % (r["frame"], r["pos_err"], r["dy"], r["yaw_err"], r["act_err"]))
    else:
        for fn in sorted(os.listdir(args.oracle_dir)):
            if fn.endswith(".jsonl"):
                rp = os.path.join(args.replay_dir, fn)
                if os.path.exists(rp):
                    print(summarize(fn[:-6], diff(os.path.join(args.oracle_dir, fn), rp)))


if __name__ == "__main__":
    sys.exit(main())
