#pragma once

#include <cstddef>

// The art sheets compiled into nf_ui (generated by cmake/EmbedArt.cmake from assets/ui).
namespace nf::ui::art_data {

struct Sheet {
    const char* name;              // file name without extension
    const unsigned char* png;
    std::size_t png_size;
    const char* manifest;          // "name x y w h" lines, '#' comments
};

extern const Sheet kSheets[];      // sorted by name
extern const std::size_t kSheetCount;

}  // namespace nf::ui::art_data
